# This is a basic workflow to help you get started with Actions

name: Mi primer workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Mi-primer-job:
    name: Mi primer job
    runs-on: ubuntu-latest
    steps:
    - name: Imprimir 
      env:
        MI_VARIABLE: Hola mundo
      run: |
        echo $MI_VARIABLE.
