# This is a basic workflow to help you get started with Actions

name: Mi primer workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Mi-primer-job:
    name: Mi primer job
    runs-on: ubuntu-latest
    # declarate a variable output on to step imprimir and outputs named respuesta 
    outputs:
      salida: ${{ steps.imprimir.outputs.respuesta }}
    steps:
    - name: Imprimir
      id: imprimir
      env:
        MI_VARIABLE: Hola mundo
      # put in variable output respuesta value of MI_VARIABLE
      run: echo "::set-output name=respuesta::${MI_VARIABLE}"
  
  Mi-segundo-job:
  # need of primer job for continue
    needs: Mi-primer-job
    name: Mi segundo job
    runs-on: ubuntu-latest
    steps:
    - name: Imprimir
      id: imprimir
      run: echo ${{needs.Mi-primer-job.outputs.salida}}


